[package]
name = "apex-ui"
version = "0.1.0"
edition = "2024"

[lib]
name = "apex_ui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
apex-core = { version = "0.1.0", path = "../apex-core" }
rust_decimal = "1.40.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
csv = "1.4.0"
tauri = { version = "2", features = [] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
tauri-plugin-dialog = "2.6.0"
arrow = "58.0.0"
axum = "0.8.9"
tower-http = { version = "0.7.0", features = ["cors"] }

[build-dependencies]
tauri-build = { version = "2", features = [] }
