[package]
name = "apex-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.44"
csv = "1.4.0"
regex = "1.12.3"
rusqlite = { version = "0.38.0", features = ["bundled"] }
rust_decimal = { version = "1.40.0", features = ["maths", "serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["raw_value"] }
sha2 = "0.10.9"
sled = "0.34.7"
uuid = { version = "1.22.0", features = ["v4"] }
